// Demo products — using stock photos (picsum.photos).
// When you have real product photos, replace the "image" values below with
// your own images placed in the /products folder (e.g. "products/cream.jpg").

// The 14 marketplace categories, in display order.
const CATEGORIES = [
  "Kadın Giyim",
  "Erkek Giyim",
  "Ayakkabı",
  "Çanta & Aksesuar",
  "Kozmetik & Kişisel Bakım",
  "Elektronik",
  "Ev & Yaşam",
  "Spor & Outdoor",
  "Anne & Bebek",
  "Pet Shop",
  "Kırtasiye & Ofis",
  "Otomotiv",
  "Hobi & Oyuncak",
  "Süpermarket",
];

const PRODUCTS = [
  {
    id: 1,
    name: "Yazlık Midi Elbise",
    description: "Dolapta 3 tane var ama bu farklı diyorsun.",
    category: "Kadın Giyim",
    price: 459,
    image: "https://picsum.photos/seed/amazoff-1/600/600",
    stock: 11,
  },
  {
    id: 2,
    name: "Yüksek Bel Kot Pantolon",
    description: "Instagram'da gördüğün pozu asla veremeyeceksin ama dene.",
    category: "Kadın Giyim",
    price: 549,
    image: "https://picsum.photos/seed/amazoff-2/600/600",
    stock: 12,
  },
  {
    id: 3,
    name: "Örme Triko Kazak",
    description: "Kışın 2 kere giyip 'kalıcı parça' diyeceğin ürün.",
    category: "Kadın Giyim",
    price: 389,
    image: "https://picsum.photos/seed/amazoff-3/600/600",
    stock: 13,
  },
  {
    id: 4,
    name: "Blazer Ceket",
    description: "Toplantıda ciddi görünmeni sağlar, toplantı hâlâ gereksizdir.",
    category: "Kadın Giyim",
    price: 699,
    image: "https://picsum.photos/seed/amazoff-4/600/600",
    stock: 14,
  },
  {
    id: 5,
    name: "Saten Gömlek",
    description: "Ütü istemez demiyoruz, sadece hayal kuruyoruz.",
    category: "Kadın Giyim",
    price: 329,
    image: "https://picsum.photos/seed/amazoff-5/600/600",
    stock: 15,
  },
  {
    id: 6,
    name: "Pileli Uzun Etek",
    description: "Rüzgarda uçuşurken çekilen 1 fotoğraf için yeterli.",
    category: "Kadın Giyim",
    price: 419,
    image: "https://picsum.photos/seed/amazoff-6/600/600",
    stock: 16,
  },
  {
    id: 7,
    name: "Crop Tişört",
    description: "Göbek deme, 'midriff reveal' de.",
    category: "Kadın Giyim",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-7/600/600",
    stock: 17,
  },
  {
    id: 8,
    name: "Triko Hırka",
    description: "Ofiste hem soğuk hem sıcak olduğunda tek çözüm.",
    category: "Kadın Giyim",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-8/600/600",
    stock: 18,
  },
  {
    id: 9,
    name: "Slim Fit Gömlek",
    description: "Aynı gömlekten 4 renk aldın, hepsi dolapta duruyor.",
    category: "Erkek Giyim",
    price: 379,
    image: "https://picsum.photos/seed/amazoff-9/600/600",
    stock: 19,
  },
  {
    id: 10,
    name: "Kargo Pantolon",
    description: "O kadar cep var ki hiçbirini kullanmıyorsun.",
    category: "Erkek Giyim",
    price: 459,
    image: "https://picsum.photos/seed/amazoff-10/600/600",
    stock: 20,
  },
  {
    id: 11,
    name: "Basic Tişört 3'lü Paket",
    description: "Beyaz tişört her zaman lazım, üçü birden değil ama neyse.",
    category: "Erkek Giyim",
    price: 299,
    image: "https://picsum.photos/seed/amazoff-11/600/600",
    stock: 21,
  },
  {
    id: 12,
    name: "Deri Ceket",
    description: "Motosikletin yok ama ceket duruyor.",
    category: "Erkek Giyim",
    price: 1299,
    image: "https://picsum.photos/seed/amazoff-12/600/600",
    stock: 22,
  },
  {
    id: 13,
    name: "Slim Fit Kot Pantolon",
    description: "Instagram algoritması yüzünden aldın, kabul et.",
    category: "Erkek Giyim",
    price: 519,
    image: "https://picsum.photos/seed/amazoff-13/600/600",
    stock: 23,
  },
  {
    id: 14,
    name: "Sweatshirt Oversize",
    description: "Rahat diye aldın, artık tek giydiğin bu.",
    category: "Erkek Giyim",
    price: 429,
    image: "https://picsum.photos/seed/amazoff-14/600/600",
    stock: 24,
  },
  {
    id: 15,
    name: "Klasik Blazer",
    description: "Düğün davetiyesi geldiğinde işine yarayacak, belki.",
    category: "Erkek Giyim",
    price: 799,
    image: "https://picsum.photos/seed/amazoff-15/600/600",
    stock: 10,
  },
  {
    id: 16,
    name: "Chino Pantolon",
    description: "Ne spor ne resmi, tam ortada bir kararsızlık.",
    category: "Erkek Giyim",
    price: 449,
    image: "https://picsum.photos/seed/amazoff-16/600/600",
    stock: 11,
  },
  {
    id: 17,
    name: "Beyaz Spor Ayakkabı",
    description: "Bir hafta beyaz kalır, sonra hayat başlar.",
    category: "Ayakkabı",
    price: 899,
    image: "https://picsum.photos/seed/amazoff-17/600/600",
    stock: 12,
  },
  {
    id: 18,
    name: "Topuklu Ayakkabı",
    description: "Kutudan çıkıp 2 saat giyilip tekrar kutuya girer.",
    category: "Ayakkabı",
    price: 649,
    image: "https://picsum.photos/seed/amazoff-18/600/600",
    stock: 13,
  },
  {
    id: 19,
    name: "Klasik Deri Ayakkabı",
    description: "Yılda bir düğünde giyilir, geri kalanı dolapta bekler.",
    category: "Ayakkabı",
    price: 999,
    image: "https://picsum.photos/seed/amazoff-19/600/600",
    stock: 14,
  },
  {
    id: 20,
    name: "Sneaker Bot",
    description: "Hem bot hem spor, kimliğini bulamamış bir ürün.",
    category: "Ayakkabı",
    price: 1099,
    image: "https://picsum.photos/seed/amazoff-20/600/600",
    stock: 15,
  },
  {
    id: 21,
    name: "Sandalet",
    description: "Yazın 3 ay, kışın hiç giyilmez ama alınır.",
    category: "Ayakkabı",
    price: 379,
    image: "https://picsum.photos/seed/amazoff-21/600/600",
    stock: 16,
  },
  {
    id: 22,
    name: "Koşu Ayakkabısı",
    description: "Koşmuyorsun ama 'koşabilirim' rahatlığı var ya.",
    category: "Ayakkabı",
    price: 1199,
    image: "https://picsum.photos/seed/amazoff-22/600/600",
    stock: 17,
  },
  {
    id: 23,
    name: "Terlik Set",
    description: "Evde bile stil sahibi olmak istiyorsan.",
    category: "Ayakkabı",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-23/600/600",
    stock: 18,
  },
  {
    id: 24,
    name: "Deri Sırt Çantası",
    description: "Laptop taşımak için aldın, süt almak için kullanıyorsun.",
    category: "Çanta & Aksesuar",
    price: 799,
    image: "https://picsum.photos/seed/amazoff-24/600/600",
    stock: 19,
  },
  {
    id: 25,
    name: "Kadın El Çantası",
    description: "İçine ne koyduğunu asla hatırlamıyorsun.",
    category: "Çanta & Aksesuar",
    price: 649,
    image: "https://picsum.photos/seed/amazoff-25/600/600",
    stock: 20,
  },
  {
    id: 26,
    name: "Güneş Gözlüğü",
    description: "Güneş yokken de takıyorsun, kabul et bu bir imaj meselesi.",
    category: "Çanta & Aksesuar",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-26/600/600",
    stock: 21,
  },
  {
    id: 27,
    name: "Kemer",
    description: "Pantolon düşmüyor ama kemer duruyor, denge böyle.",
    category: "Çanta & Aksesuar",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-27/600/600",
    stock: 22,
  },
  {
    id: 28,
    name: "Bel Çantası 2000'ler Esintili",
    description: "Nostalji mi moda mı karar veremedik, ikisi de olsun.",
    category: "Çanta & Aksesuar",
    price: 259,
    image: "https://picsum.photos/seed/amazoff-28/600/600",
    stock: 23,
  },
  {
    id: 29,
    name: "Cüzdan",
    description: "Nakit taşımıyorsun ama cüzdan lazım, mantık böyle işliyor.",
    category: "Çanta & Aksesuar",
    price: 289,
    image: "https://picsum.photos/seed/amazoff-29/600/600",
    stock: 24,
  },
  {
    id: 30,
    name: "Şapka",
    description: "Kötü saç günü kurtarıcısı, her gün kötü saç günü gibi kullanılıyor.",
    category: "Çanta & Aksesuar",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-30/600/600",
    stock: 10,
  },
  {
    id: 31,
    name: "Nemlendirici Yüz Kremi",
    description: "Cilt bakımı rutini 1. adım, rutin hiç bitmiyor.",
    category: "Kozmetik & Kişisel Bakım",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-31/600/600",
    stock: 11,
  },
  {
    id: 32,
    name: "Dudak Parlatıcısı",
    description: "Bir tane yeter derken 6. tanesini alıyorsun.",
    category: "Kozmetik & Kişisel Bakım",
    price: 129,
    image: "https://picsum.photos/seed/amazoff-32/600/600",
    stock: 12,
  },
  {
    id: 33,
    name: "Mat Ruj - Kiremit",
    description: "Video call'da güzel görünmek için yeterli sebep.",
    category: "Kozmetik & Kişisel Bakım",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-33/600/600",
    stock: 13,
  },
  {
    id: 34,
    name: "Parfüm 50ml",
    description: "Koku hafızası güçlüdür derler, cüzdan hafızası daha güçlü olsun.",
    category: "Kozmetik & Kişisel Bakım",
    price: 899,
    image: "https://picsum.photos/seed/amazoff-34/600/600",
    stock: 14,
  },
  {
    id: 35,
    name: "Cilt Bakım Seti",
    description: "5 adımlı rutin, gerçekte 2 adımda pes ediyorsun.",
    category: "Kozmetik & Kişisel Bakım",
    price: 549,
    image: "https://picsum.photos/seed/amazoff-35/600/600",
    stock: 15,
  },
  {
    id: 36,
    name: "Saç Bakım Yağı",
    description: "Saçların ipeksi olacak, en azından reklamda öyle.",
    category: "Kozmetik & Kişisel Bakım",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-36/600/600",
    stock: 16,
  },
  {
    id: 37,
    name: "Güneş Kremi SPF50",
    description: "Bir kere sürüp şişeyi bir yıl saklayan tipsen bu tam sana göre.",
    category: "Kozmetik & Kişisel Bakım",
    price: 249,
    image: "https://picsum.photos/seed/amazoff-37/600/600",
    stock: 17,
  },
  {
    id: 38,
    name: "Makyaj Fırça Seti",
    description: "Kaç tanesini kullanıyorsun? İkisi. Kaç tane aldın? On iki.",
    category: "Kozmetik & Kişisel Bakım",
    price: 379,
    image: "https://picsum.photos/seed/amazoff-38/600/600",
    stock: 18,
  },
  {
    id: 39,
    name: "Kablosuz Kulaklık",
    description: "Sessizliği satın alıyorsun, aslında.",
    category: "Elektronik",
    price: 1299,
    image: "https://picsum.photos/seed/amazoff-39/600/600",
    stock: 19,
  },
  {
    id: 40,
    name: "Akıllı Bileklik",
    description: "10.000 adım hedefine hiç ulaşmadın ama takip ediyorsun.",
    category: "Elektronik",
    price: 899,
    image: "https://picsum.photos/seed/amazoff-40/600/600",
    stock: 20,
  },
  {
    id: 41,
    name: "Taşınabilir Şarj Cihazı",
    description: "Çantada duruyor, tam lazım olduğunda şarjı bitik çıkıyor.",
    category: "Elektronik",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-41/600/600",
    stock: 21,
  },
  {
    id: 42,
    name: "Bluetooth Hoparlör",
    description: "Duşta konser veriyorsun, komşular minnettar değil.",
    category: "Elektronik",
    price: 749,
    image: "https://picsum.photos/seed/amazoff-42/600/600",
    stock: 22,
  },
  {
    id: 43,
    name: "Mekanik Klavye",
    description: "Klik sesi mesai arkadaşlarının en sevdiği şey, tabii ki değil.",
    category: "Elektronik",
    price: 1599,
    image: "https://picsum.photos/seed/amazoff-43/600/600",
    stock: 23,
  },
  {
    id: 44,
    name: "Kablosuz Mouse",
    description: "Kablosuz özgürlük, pil bitene kadar.",
    category: "Elektronik",
    price: 399,
    image: "https://picsum.photos/seed/amazoff-44/600/600",
    stock: 24,
  },
  {
    id: 45,
    name: "Telefon Kılıfı",
    description: "Telefonu düşürmene neden olan asıl şey bu kılıfın kalınlığı.",
    category: "Elektronik",
    price: 129,
    image: "https://picsum.photos/seed/amazoff-45/600/600",
    stock: 10,
  },
  {
    id: 46,
    name: "USB-C Çoklu Adaptör",
    description: "Kaç tane girişe ihtiyacın var ki, hepsine.",
    category: "Elektronik",
    price: 449,
    image: "https://picsum.photos/seed/amazoff-46/600/600",
    stock: 11,
  },
  {
    id: 47,
    name: "Aromaterapi Mum Seti",
    description: "Ev spa'ya dönüşüyor, 20 dakikalığına.",
    category: "Ev & Yaşam",
    price: 279,
    image: "https://picsum.photos/seed/amazoff-47/600/600",
    stock: 12,
  },
  {
    id: 48,
    name: "Dekoratif Yastık Kılıfı",
    description: "Kanepede oturmayı yasaklayan estetik obje.",
    category: "Ev & Yaşam",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-48/600/600",
    stock: 13,
  },
  {
    id: 49,
    name: "Mutfak Bıçak Seti",
    description: "Şef gibi doğruyorsun, şef gibi değil.",
    category: "Ev & Yaşam",
    price: 599,
    image: "https://picsum.photos/seed/amazoff-49/600/600",
    stock: 14,
  },
  {
    id: 50,
    name: "Battaniye Peluş",
    description: "Kışın tek arkadaşın, yazın dolapta unutulan.",
    category: "Ev & Yaşam",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-50/600/600",
    stock: 15,
  },
  {
    id: 51,
    name: "Duvar Saati Minimalist",
    description: "Telefon varken saate bakan tek insansın.",
    category: "Ev & Yaşam",
    price: 429,
    image: "https://picsum.photos/seed/amazoff-51/600/600",
    stock: 16,
  },
  {
    id: 52,
    name: "Bitki Saksısı Seti",
    description: "3 bitki aldın, 2'si hayatta, biri 'dinleniyor'.",
    category: "Ev & Yaşam",
    price: 259,
    image: "https://picsum.photos/seed/amazoff-52/600/600",
    stock: 17,
  },
  {
    id: 53,
    name: "Difüzör Set",
    description: "Ev kokusu senin kişiliğin oldu artık.",
    category: "Ev & Yaşam",
    price: 329,
    image: "https://picsum.photos/seed/amazoff-53/600/600",
    stock: 18,
  },
  {
    id: 54,
    name: "Organizasyon Kutusu Seti",
    description: "Düzenli görünmek, düzenli olmaktan daha kolay.",
    category: "Ev & Yaşam",
    price: 379,
    image: "https://picsum.photos/seed/amazoff-54/600/600",
    stock: 19,
  },
  {
    id: 55,
    name: "Yoga Matı",
    description: "Bir kere yoga yaptın, mat artık dekor oldu.",
    category: "Spor & Outdoor",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-55/600/600",
    stock: 20,
  },
  {
    id: 56,
    name: "Fitness Eldiveni",
    description: "Spor salonuna gitmiyorsun ama eldiven hazır.",
    category: "Spor & Outdoor",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-56/600/600",
    stock: 21,
  },
  {
    id: 57,
    name: "Kamp Çadırı 2 Kişilik",
    description: "Bir kez kamp yaptın, çadır balkonda kaldı.",
    category: "Spor & Outdoor",
    price: 1899,
    image: "https://picsum.photos/seed/amazoff-57/600/600",
    stock: 22,
  },
  {
    id: 58,
    name: "Termos 1L",
    description: "Suyu sıcak tutuyor, motivasyonunu tutmuyor.",
    category: "Spor & Outdoor",
    price: 249,
    image: "https://picsum.photos/seed/amazoff-58/600/600",
    stock: 23,
  },
  {
    id: 59,
    name: "Spor Çantası",
    description: "Spor kıyafetleri içinde 3 ay değişmeden duruyor.",
    category: "Spor & Outdoor",
    price: 299,
    image: "https://picsum.photos/seed/amazoff-59/600/600",
    stock: 24,
  },
  {
    id: 60,
    name: "Bisiklet Kilidi",
    description: "Bisiklet çalınmasın diye aldın, bisiklete binmiyorsun ki.",
    category: "Spor & Outdoor",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-60/600/600",
    stock: 10,
  },
  {
    id: 61,
    name: "Direnç Bandı Seti",
    description: "Evde spor yapacaktın, bant hâlâ ambalajında.",
    category: "Spor & Outdoor",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-61/600/600",
    stock: 11,
  },
  {
    id: 62,
    name: "Bebek Battaniyesi",
    description: "Bebekten çok sen üşüyorsun galiba.",
    category: "Anne & Bebek",
    price: 299,
    image: "https://picsum.photos/seed/amazoff-62/600/600",
    stock: 12,
  },
  {
    id: 63,
    name: "Emzik Seti",
    description: "Bebeğin en sevdiği aksesuar, senin en çok aradığın eşya.",
    category: "Anne & Bebek",
    price: 129,
    image: "https://picsum.photos/seed/amazoff-63/600/600",
    stock: 13,
  },
  {
    id: 64,
    name: "Bebek Bakım Seti",
    description: "Kutuyu açtın, hepsini kullanmadın, olsun.",
    category: "Anne & Bebek",
    price: 449,
    image: "https://picsum.photos/seed/amazoff-64/600/600",
    stock: 14,
  },
  {
    id: 65,
    name: "Mama Sandalyesi",
    description: "Bebek 10 dakika oturuyor, sandalye ömür boyu duruyor.",
    category: "Anne & Bebek",
    price: 1599,
    image: "https://picsum.photos/seed/amazoff-65/600/600",
    stock: 15,
  },
  {
    id: 66,
    name: "Bebek Oyun Halısı",
    description: "Bebekten çok sen yatıyorsun üzerinde.",
    category: "Anne & Bebek",
    price: 549,
    image: "https://picsum.photos/seed/amazoff-66/600/600",
    stock: 16,
  },
  {
    id: 67,
    name: "Biberon Seti",
    description: "Kaç biberon lazım? Bilmiyoruz, hepsini alalım.",
    category: "Anne & Bebek",
    price: 249,
    image: "https://picsum.photos/seed/amazoff-67/600/600",
    stock: 17,
  },
  {
    id: 68,
    name: "Bebek Taşıma Çantası",
    description: "İçinde bebek eşyası mı taşınıyor yoksa senin tüm hayatın mı belli değil.",
    category: "Anne & Bebek",
    price: 399,
    image: "https://picsum.photos/seed/amazoff-68/600/600",
    stock: 18,
  },
  {
    id: 69,
    name: "Kedi Tırmalama Tahtası",
    description: "Koltuğu tırmalamasın diye aldın, koltuğu hâlâ tırmalıyor.",
    category: "Pet Shop",
    price: 399,
    image: "https://picsum.photos/seed/amazoff-69/600/600",
    stock: 19,
  },
  {
    id: 70,
    name: "Köpek Maması 3kg",
    description: "Dört ayaklı aile üyesi senden iyi besleniyor.",
    category: "Pet Shop",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-70/600/600",
    stock: 20,
  },
  {
    id: 71,
    name: "Evcil Hayvan Taşıma Çantası",
    description: "Veterinere giderken kullanılan tek eşya.",
    category: "Pet Shop",
    price: 449,
    image: "https://picsum.photos/seed/amazoff-71/600/600",
    stock: 21,
  },
  {
    id: 72,
    name: "Kedi Kumu 10L",
    description: "Koku yok diyor reklam, koku her zaman var.",
    category: "Pet Shop",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-72/600/600",
    stock: 22,
  },
  {
    id: 73,
    name: "Köpek Tasması",
    description: "Şık görünüyor, köpeğin umurunda değil.",
    category: "Pet Shop",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-73/600/600",
    stock: 23,
  },
  {
    id: 74,
    name: "Kedi Oyuncak Seti",
    description: "Oyuncaklar dururken kutunun kendisiyle oynuyor.",
    category: "Pet Shop",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-74/600/600",
    stock: 24,
  },
  {
    id: 75,
    name: "A5 Defter Set",
    description: "Günlük tutacaktın, 3 sayfa yazıp bıraktın.",
    category: "Kırtasiye & Ofis",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-75/600/600",
    stock: 10,
  },
  {
    id: 76,
    name: "Gel Kalem 12'li Set",
    description: "12 renk aldın, sadece siyahı kullanıyorsun.",
    category: "Kırtasiye & Ofis",
    price: 89,
    image: "https://picsum.photos/seed/amazoff-76/600/600",
    stock: 11,
  },
  {
    id: 77,
    name: "Masaüstü Organizer",
    description: "Düzenli masa, düzensiz hayat.",
    category: "Kırtasiye & Ofis",
    price: 229,
    image: "https://picsum.photos/seed/amazoff-77/600/600",
    stock: 12,
  },
  {
    id: 78,
    name: "Planlayıcı Ajanda",
    description: "Ocak ayı dolu, şubat boş kaldı.",
    category: "Kırtasiye & Ofis",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-78/600/600",
    stock: 13,
  },
  {
    id: 79,
    name: "Sticky Not Seti",
    description: "Ofis masan artık sanat enstalasyonu gibi.",
    category: "Kırtasiye & Ofis",
    price: 79,
    image: "https://picsum.photos/seed/amazoff-79/600/600",
    stock: 14,
  },
  {
    id: 80,
    name: "Mekanik Kurşun Kalem Seti",
    description: "Yazı yazmıyorsun ama estetik duruyor.",
    category: "Kırtasiye & Ofis",
    price: 129,
    image: "https://picsum.photos/seed/amazoff-80/600/600",
    stock: 15,
  },
  {
    id: 81,
    name: "Araç İç Temizlik Seti",
    description: "Bir kez kullandın, araç yine toz içinde.",
    category: "Otomotiv",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-81/600/600",
    stock: 16,
  },
  {
    id: 82,
    name: "Telefon Tutucu Araç İçi",
    description: "GPS için aldın, sadece müzik için kullanıyorsun.",
    category: "Otomotiv",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-82/600/600",
    stock: 17,
  },
  {
    id: 83,
    name: "Oto Koku Seti",
    description: "Araba artık spa gibi kokuyor, yol hâlâ trafik.",
    category: "Otomotiv",
    price: 99,
    image: "https://picsum.photos/seed/amazoff-83/600/600",
    stock: 18,
  },
  {
    id: 84,
    name: "Araç Şarj Adaptörü",
    description: "İki USB girişi, hep tek telefonun var.",
    category: "Otomotiv",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-84/600/600",
    stock: 19,
  },
  {
    id: 85,
    name: "Direksiyon Kılıfı",
    description: "Elin terli olduğunda tek faydası oluyor.",
    category: "Otomotiv",
    price: 229,
    image: "https://picsum.photos/seed/amazoff-85/600/600",
    stock: 20,
  },
  {
    id: 86,
    name: "Bagaj Organizer",
    description: "Bagaj düzenli, arka koltuk hâlâ dağınık.",
    category: "Otomotiv",
    price: 279,
    image: "https://picsum.photos/seed/amazoff-86/600/600",
    stock: 21,
  },
  {
    id: 87,
    name: "1000 Parça Puzzle",
    description: "Kutudan çıkarıp yarısında bıraktığın klasik.",
    category: "Hobi & Oyuncak",
    price: 249,
    image: "https://picsum.photos/seed/amazoff-87/600/600",
    stock: 22,
  },
  {
    id: 88,
    name: "Model Uçak Seti",
    description: "Yapacaktın, kutu hâlâ raftan inmedi.",
    category: "Hobi & Oyuncak",
    price: 399,
    image: "https://picsum.photos/seed/amazoff-88/600/600",
    stock: 23,
  },
  {
    id: 89,
    name: "Uzaktan Kumandalı Araba",
    description: "Yetişkin aldı, 'çocuğa' diye açıklıyor.",
    category: "Hobi & Oyuncak",
    price: 599,
    image: "https://picsum.photos/seed/amazoff-89/600/600",
    stock: 24,
  },
  {
    id: 90,
    name: "Boyama Seti Yetişkin",
    description: "Stres atmak için aldın, stresle boyuyorsun.",
    category: "Hobi & Oyuncak",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-90/600/600",
    stock: 10,
  },
  {
    id: 91,
    name: "Satranç Takımı",
    description: "Kurallarını hâlâ tam bilmiyorsun ama şık duruyor.",
    category: "Hobi & Oyuncak",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-91/600/600",
    stock: 11,
  },
  {
    id: 92,
    name: "Lego Uyumlu Yapı Seti",
    description: "Kutudan hiç çıkmadı ama 'ileride' lazım olacak.",
    category: "Hobi & Oyuncak",
    price: 449,
    image: "https://picsum.photos/seed/amazoff-92/600/600",
    stock: 12,
  },
  {
    id: 93,
    name: "Organik Bal 850g",
    description: "Organik yazınca fiyat 3 katına çıkıyor, alıyorsun yine de.",
    category: "Süpermarket",
    price: 289,
    image: "https://picsum.photos/seed/amazoff-93/600/600",
    stock: 13,
  },
  {
    id: 94,
    name: "Kahve Çekirdeği 1kg",
    description: "Barista gibi demliyorsun, tadı yine de nescafe gibi.",
    category: "Süpermarket",
    price: 349,
    image: "https://picsum.photos/seed/amazoff-94/600/600",
    stock: 14,
  },
  {
    id: 95,
    name: "Bitki Çayı Seti",
    description: "Sağlıklı yaşam bu çaylarla başlıyor, sözde.",
    category: "Süpermarket",
    price: 149,
    image: "https://picsum.photos/seed/amazoff-95/600/600",
    stock: 15,
  },
  {
    id: 96,
    name: "Kuruyemiş Karışık 500g",
    description: "Sağlıklı atıştırmalık, poşeti bitirene kadar sağlıklı kalıyor.",
    category: "Süpermarket",
    price: 199,
    image: "https://picsum.photos/seed/amazoff-96/600/600",
    stock: 16,
  },
  {
    id: 97,
    name: "Zeytinyağı 1L",
    description: "Soğuk sıkım yazınca elin cebe gidiyor.",
    category: "Süpermarket",
    price: 259,
    image: "https://picsum.photos/seed/amazoff-97/600/600",
    stock: 17,
  },
  {
    id: 98,
    name: "Bal Kavanozu Hediyelik Set",
    description: "Hediye almak bahane, kendine aldığını biliyoruz.",
    category: "Süpermarket",
    price: 329,
    image: "https://picsum.photos/seed/amazoff-98/600/600",
    stock: 18,
  },
  {
    id: 99,
    name: "Makarna Çeşitleri Seti",
    description: "İtalyan mutfağına 1 adım, İtalya'ya 0 adım.",
    category: "Süpermarket",
    price: 179,
    image: "https://picsum.photos/seed/amazoff-99/600/600",
    stock: 19,
  },
  {
    id: 100,
    name: "Baharat Seti 12'li",
    description: "Hepsini kullanmıyorsun ama raf çok güzel duruyor.",
    category: "Süpermarket",
    price: 249,
    image: "https://picsum.photos/seed/amazoff-100/600/600",
    stock: 20,
  },
];

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === Number(id));
}

function getProductsByCategory(category) {
  return PRODUCTS.filter((p) => p.category === category);
}

function searchProducts(query) {
  const q = query.trim().toLocaleLowerCase("tr-TR");
  if (!q) return PRODUCTS;
  return PRODUCTS.filter((p) =>
    p.name.toLocaleLowerCase("tr-TR").includes(q) ||
    p.category.toLocaleLowerCase("tr-TR").includes(q) ||
    p.description.toLocaleLowerCase("tr-TR").includes(q)
  );
}
